"""add user data

Revision ID: 17ff0663bc3f
Revises: 47dc6e9da235
Create Date: 2025-12-17 14:39:40.850869

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17ff0663bc3f"
down_revision: str | Sequence[str] | None = "47dc6e9da235"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=20), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("role", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_column("users", "password")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
