"""remove password char limit

Revision ID: e56751fa3090
Revises: 17ff0663bc3f
Create Date: 2025-12-17 16:05:11.764236

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e56751fa3090"
down_revision: str | Sequence[str] | None = "17ff0663bc3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
